//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Donations')
export class DonationsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  donationId: string;

  @Column('text', { nullable: true })
  itemName: string;

  @Column('integer', { nullable: true })
  quantityDonated: number;
}
