//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    InventoryItems: [
      { itemName: 'itemName 1', quantity: 1, status: 'status 1', id: 38 },
      { itemName: 'itemName 2', quantity: 2, status: 'status 2', id: 62 },
      { itemName: 'itemName 3', quantity: 3, status: 'status 3', id: 54 },
      { itemName: 'itemName 4', quantity: 4, status: 'status 4', id: 31 },
      { itemName: 'itemName 5', quantity: 5, status: 'status 5', id: 54 },
    ],
    Donations: [
      {
        donationId: 'donationId 1',
        itemName: 'itemName 1',
        quantityDonated: 1,
        id: 9,
      },
      {
        donationId: 'donationId 2',
        itemName: 'itemName 2',
        quantityDonated: 2,
        id: 52,
      },
      {
        donationId: 'donationId 3',
        itemName: 'itemName 3',
        quantityDonated: 3,
        id: 56,
      },
      {
        donationId: 'donationId 4',
        itemName: 'itemName 4',
        quantityDonated: 4,
        id: 23,
      },
      {
        donationId: 'donationId 5',
        itemName: 'itemName 5',
        quantityDonated: 5,
        id: 100,
      },
    ],
    Users: [
      { name: 'name 1', email: 'email 1', phoneNo: 'phoneNo 1', id: 30 },
      { name: 'name 2', email: 'email 2', phoneNo: 'phoneNo 2', id: 26 },
      { name: 'name 3', email: 'email 3', phoneNo: 'phoneNo 3', id: 2 },
      { name: 'name 4', email: 'email 4', phoneNo: 'phoneNo 4', id: 2 },
      { name: 'name 5', email: 'email 5', phoneNo: 'phoneNo 5', id: 89 },
    ],
  },
};
export default data;
