//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    InventoryItems: {
      name: 'Inventory Items',
      fields: {
        itemName: 'Item Name',
        quantity: 'Quantity',
        status: 'Status',
        id: 'id',
      },
    },
    Donations: {
      name: 'Donations',
      fields: {
        donationId: 'Donation Id',
        itemName: 'Item Name',
        quantityDonated: 'Quantity Donated',
        id: 'id',
      },
    },
    Users: {
      name: 'Users',
      fields: { name: 'Name', email: 'Email', phoneNo: 'Phone No', id: 'id' },
    },
  },
};
const frResources = {
  resources: {
    InventoryItems: {
      name: 'Inventory Items (fr)',
      fields: {
        itemName: 'Item Name (fr)',
        quantity: 'Quantity (fr)',
        status: 'Status (fr)',
        id: 'id',
      },
    },
    Donations: {
      name: 'Donations (fr)',
      fields: {
        donationId: 'Donation Id (fr)',
        itemName: 'Item Name (fr)',
        quantityDonated: 'Quantity Donated (fr)',
        id: 'id',
      },
    },
    Users: {
      name: 'Users (fr)',
      fields: {
        name: 'Name (fr)',
        email: 'Email (fr)',
        phoneNo: 'Phone No (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
